name: momo_vn
description: Integrate open MoMo.VN application for payment. Once completed, the system will record data of success or failure. From there handle the next step.
version: 2.0.2
#author: Vo Ngoc Minh <minhvo.me@gmail.com>
homepage: https://github.com/minhvn/momo.vn

analyzer:
  enable-experiment:
    - non-nullable

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  eventify: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.minh.momo_vn
        pluginClass: MomoVnPlugin
      ios:
        pluginClass: MomoVnPlugin
